from __future__ import annotations

AVAIL_OBSERVED_ACTIVE = 1
AVAIL_OBSERVED_FLAT = 2
AVAIL_STRUCTURALLY_MISSING = 3
AVAIL_FORCED_ZERO_BY_PORTFOLIO = 4
AVAIL_FORCED_CASH_BY_RISK = 5
AVAIL_INVALIDATED_BY_DQ = 6

BASE_AVAIL_ACTIVE_CODES = (AVAIL_OBSERVED_ACTIVE, AVAIL_OBSERVED_FLAT)
BASE_AVAIL_INACTIVE_CODES = (AVAIL_STRUCTURALLY_MISSING, AVAIL_INVALIDATED_BY_DQ)
BASE_AVAIL_ALLOWED_CODES = BASE_AVAIL_ACTIVE_CODES + BASE_AVAIL_INACTIVE_CODES
PATH_AVAIL_INACTIVE_CODES = (
    AVAIL_STRUCTURALLY_MISSING,
    AVAIL_FORCED_ZERO_BY_PORTFOLIO,
    AVAIL_FORCED_CASH_BY_RISK,
    AVAIL_INVALIDATED_BY_DQ,
)
PATH_AVAIL_ALLOWED_CODES = BASE_AVAIL_ALLOWED_CODES + (
    AVAIL_FORCED_ZERO_BY_PORTFOLIO,
    AVAIL_FORCED_CASH_BY_RISK,
)

ROLLOUT1_EXECUTION_OVERLAP_WEIGHTS = {
    "symbol_support": 0.25,
    "activity": 0.35,
    "gross": 0.25,
    "rebalance": 0.15,
}

MODULE6_CONSTRAINT_POLICY_VERSION = "zimtra_portfolio_v1"
MODULE6_OVERNIGHT_POLICY_VERSION = "module6_overnight_v1"
MODULE6_FRICTION_POLICY_VERSION = "module6_portfolio_friction_v1"
MODULE6_RANKING_POLICY_VERSION = "module6_ranking_v1"
MODULE6_SUPPORT_POLICY_VERSION = "module6_support_v1"
